### ISSUE TITLE
What's the difference between the two models?

### ISSUE THREAD

**Issue by wangtss** [naver/dope#4]
I test the two models and find that DOPE_v1_0_0's result is much better than the realtime model, also much slower. But the two model's size and parameters are the same, so can you please tell me what are the difference between two?

**Comment by PhilippeWeinzaepfel** [comment]
The differences are mentioned in the "runtime" paragraph of Section 3.3 in our [paper](https://arxiv.org/pdf/2008.09457.pdf).
In the real-time model:
(a) the input data is rescaled to a lower dimension (400 px minimum size instead if 800 px for the other model)
(b) the number of proposals output by the RPN is reduced to 50 (instead of 1000 for the other model)
(c) it uses half precision computation (at test time only)
Note that none of this changes the model parameters but significantly changes the number of flops.
